// The versioned price/window table in scripts/pricing.mjs — the single place prices live —
// and the coverage guard that says the table knows every model id a doctor corpus recorded.
import test from "node:test";
import assert from "node:assert/strict";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { PRICING, priceFor } from "../../scripts/pricing.mjs";
import { collectModelIds, formatFixture, readFixture, unpricedIds } from "../../scripts/refresh-observed-models.mjs";

const FIXTURE = fileURLToPath(new URL("../fixtures/observed-model-ids.json", import.meta.url));
const REFRESH = fileURLToPath(new URL("../../scripts/refresh-observed-models.mjs", import.meta.url));
// A committed corpus of transcript records in the same <slug>/<session>.jsonl layout as
// ~/.claude/projects, holding the model ids the snapshot may never drop. It is the snapshot's
// independent counterpart: keeping the two in step takes an edit to both, which is what lets the
// snapshot guard below fail on a lone hand edit to the snapshot.
const CORPUS = fileURLToPath(new URL("../fixtures/observed-corpus", import.meta.url));

// A transcript record shaped like the ones doctor counts: assistant side, carrying usage.
const turn = (model) =>
  JSON.stringify({ type: "assistant", message: { model, usage: { input_tokens: 1, output_tokens: 1 }, content: [] } });

// Builds a throwaway corpus in the same <slug>/<session>.jsonl layout as ~/.claude/projects.
// Every test that reads a corpus reads one of these, never the operator's real one.
function corpus(sessions) {
  const root = mkdtempSync(join(tmpdir(), "observed-models-"));
  for (const [name, lines] of Object.entries(sessions)) {
    const slug = join(root, "repo-slug");
    mkdirSync(slug, { recursive: true });
    writeFileSync(join(slug, `${name}.jsonl`), lines.join("\n") + "\n");
  }
  return root;
}

test("PRICING: asOf is an ISO date", () => {
  assert.match(PRICING.asOf, /^\d{4}-\d{2}-\d{2}$/);
  assert.ok(!Number.isNaN(Date.parse(PRICING.asOf)));
});

test("PRICING: every entry carries input price, output price, and context window", () => {
  const ids = Object.keys(PRICING.models);
  assert.ok(ids.length >= 5, "the measured corpus uses at least five model ids");
  for (const id of ids) {
    const m = PRICING.models[id];
    assert.equal(typeof m.in, "number", `${id}.in`);
    assert.equal(typeof m.out, "number", `${id}.out`);
    assert.equal(typeof m.window, "number", `${id}.window`);
    assert.ok(m.in > 0 && m.out > 0 && m.window > 0, `${id} has positive values`);
  }
});

// The fixture is a snapshot of the model ids a real doctor corpus recorded, regenerated by
// `node scripts/refresh-observed-models.mjs` — not a restatement of PRICING.models' own keys,
// which would make this assertion compare a list to itself and never fail.
test("PRICING: covers every model id in the observed-ids snapshot (tests/fixtures/observed-model-ids.json)", () => {
  const observed = readFixture(FIXTURE);
  assert.ok(observed.length >= 6, "the snapshot lists the observed ids");
  assert.deepEqual(unpricedIds(observed), [], "every observed model id is priced");
});

test("the coverage guard reports a snapshot id that is genuinely unpriced", () => {
  const dir = mkdtempSync(join(tmpdir(), "observed-models-"));
  const path = join(dir, "observed-model-ids.json");
  writeFileSync(path, formatFixture(["claude-opus-5", "claude-nimbus-9"]));
  try {
    assert.deepEqual(unpricedIds(readFixture(path)), ["claude-nimbus-9"]);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

// All this compares is the file against a re-render of its own contents, so it pins the writer's
// shape and nothing about where the contents came from. It used to be named "byte-for-byte what
// the refresh script writes", which claimed the guard below — and passed on any well-formed hand
// edit, including deleting an observed id.
test("the snapshot on disk is in the refresh script's canonical shape: sorted, deduped, two-space", () => {
  assert.equal(readFileSync(FIXTURE, "utf8"), formatFixture(readFixture(FIXTURE)));
});

// The guard that survives a hand edit: run the real refresh script over the committed corpus and
// require the snapshot to hold every id it reports. Deleting an observed id from the snapshot —
// the edit that would disarm the coverage guard above by removing whatever is unpriced — fails
// here, because the corpus still records it.
test("the committed snapshot holds every model id the refresh script derives from the fixture corpus", () => {
  const root = mkdtempSync(join(tmpdir(), "observed-models-"));
  const out = join(root, "out.json");
  const r = spawnSync(process.execPath, [REFRESH, "--dir", CORPUS, "--out", out], {
    encoding: "utf8",
    env: { ...process.env, HOME: root }, // never the operator's real ~/.claude/projects
  });
  try {
    assert.equal(r.status, 0, r.stderr);
    const derived = readFixture(out);
    assert.ok(derived.length >= 6, "the fixture corpus records the observed ids");
    const snapshot = new Set(readFixture(FIXTURE));
    const missing = derived.filter((id) => !snapshot.has(id));
    assert.deepEqual(missing, [],
      `tests/fixtures/observed-model-ids.json is missing corpus id(s) ${missing.join(", ")} — `
      + "regenerate it with scripts/refresh-observed-models.mjs instead of editing it by hand");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// What keeps the guard above compatible with the documented refresh: the refresh is additive. It
// adds whatever the corpus it read records and keeps every id the snapshot already held, so a
// machine whose transcripts never mention the frozen corpus ids cannot drop them.
test("refresh CLI: a refresh adds what the corpus records and keeps the ids the snapshot already held", () => {
  const root = corpus({ "sess-one": [turn("claude-opus-5"), turn("claude-nimbus-9")] });
  const out = join(root, "out.json");
  writeFileSync(out, formatFixture(["claude-fable-5", "claude-sonnet-5"]));
  const r = spawnSync(process.execPath, [REFRESH, "--dir", root, "--out", out], {
    encoding: "utf8",
    env: { ...process.env, HOME: root },
  });
  try {
    assert.equal(r.status, 0, r.stderr);
    assert.deepEqual(readFixture(out),
      ["claude-fable-5", "claude-nimbus-9", "claude-opus-5", "claude-sonnet-5"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// The collision stated end to end: run the documented refresh over a machine whose transcripts
// record none of the fixture corpus's ids, and the guard above still holds afterwards. A refresh
// that replaced the snapshot would red the tree here, with no way to tell that from a genuine
// coverage regression.
test("refresh CLI: the documented refresh over a foreign corpus keeps the snapshot a superset of the fixture corpus", () => {
  const root = corpus({ "sess-one": [turn("claude-opus-5")] });
  const refreshed = join(root, "snapshot.json");
  const derived = join(root, "corpus-ids.json");
  writeFileSync(refreshed, readFileSync(FIXTURE, "utf8"));
  try {
    for (const [dir, out] of [[root, refreshed], [CORPUS, derived]]) {
      const r = spawnSync(process.execPath, [REFRESH, "--dir", dir, "--out", out], {
        encoding: "utf8",
        env: { ...process.env, HOME: root },
      });
      assert.equal(r.status, 0, r.stderr);
    }
    const snapshot = new Set(readFixture(refreshed));
    const missing = readFixture(derived).filter((id) => !snapshot.has(id));
    assert.deepEqual(missing, [], "the documented refresh dropped fixture-corpus id(s) the guard requires");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("refresh: collects the model ids a corpus recorded, sorted and deduped", () => {
  const root = corpus({
    "sess-one": [turn("claude-sonnet-5"), turn("claude-opus-5"), turn("claude-opus-5")],
    "sess-two": [turn("claude-opus-5")],
  });
  try {
    assert.deepEqual(collectModelIds(root), ["claude-opus-5", "claude-sonnet-5"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("refresh: skips synthetic placeholders and records that are not priced turns", () => {
  const root = corpus({
    "sess-one": [
      turn("claude-opus-5"),
      turn("<synthetic>"),
      JSON.stringify({ type: "user", message: { model: "claude-typed-by-a-human", content: [] } }),
      JSON.stringify({ type: "assistant", message: { model: "claude-no-usage", content: [] } }),
    ],
  });
  try {
    assert.deepEqual(collectModelIds(root), ["claude-opus-5"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// The whole point of deriving the snapshot from a corpus: an id the table has never heard of
// must reach the fixture, so the coverage assertion above can go red on it.
test("refresh: keeps an observed id the price table does not know", () => {
  const root = corpus({ "sess-one": [turn("claude-opus-5"), turn("claude-nimbus-9")] });
  try {
    const ids = collectModelIds(root);
    assert.ok(ids.includes("claude-nimbus-9"), "an unpriced observed id is collected, not filtered out");
    assert.deepEqual(unpricedIds(ids), ["claude-nimbus-9"]);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("refresh CLI: --dir reads the named corpus and --out writes the snapshot there", () => {
  const root = corpus({ "sess-one": [turn("claude-sonnet-5"), turn("claude-opus-5")] });
  const out = join(root, "out.json");
  const r = spawnSync(process.execPath, [REFRESH, "--dir", root, "--out", out], {
    encoding: "utf8",
    env: { ...process.env, HOME: root }, // a bug that ignored --dir would read this, not the real home
  });
  try {
    assert.equal(r.status, 0, r.stderr);
    assert.equal(readFileSync(out, "utf8"), formatFixture(["claude-opus-5", "claude-sonnet-5"]));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// An empty snapshot would disarm the guard silently — exactly the failure this task exists to fix.
test("refresh CLI: refuses to write an empty snapshot when the corpus yields no ids", () => {
  const root = mkdtempSync(join(tmpdir(), "observed-models-"));
  const out = join(root, "out.json");
  const r = spawnSync(process.execPath, [REFRESH, "--dir", join(root, "no-such-corpus"), "--out", out], {
    encoding: "utf8",
    env: { ...process.env, HOME: root },
  });
  try {
    assert.notEqual(r.status, 0, "an empty corpus is an error, not an empty fixture");
    assert.equal(existsSync(out), false, "nothing is written");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// findTranscriptFiles re-throws a permissions or I/O failure rather than reading it as an empty
// corpus, so main has to report it in the script's own voice like every other failure path here.
test("refresh CLI: an unreadable corpus reports the script's prefixed error, not a stack trace", {
  skip: process.getuid?.() === 0 ? "root reads a directory whose permission bits forbid it" : false,
}, () => {
  const root = mkdtempSync(join(tmpdir(), "observed-models-"));
  const locked = join(root, "corpus", "repo-slug");
  mkdirSync(locked, { recursive: true });
  writeFileSync(join(locked, "sess-one.jsonl"), turn("claude-opus-5") + "\n");
  chmodSync(locked, 0o000);
  const out = join(root, "out.json");
  const r = spawnSync(process.execPath, [REFRESH, "--dir", join(root, "corpus"), "--out", out], {
    encoding: "utf8",
    env: { ...process.env, HOME: root },
  });
  try {
    assert.notEqual(r.status, 0, "an unreadable corpus is an error");
    assert.match(r.stderr, /^refresh-observed-models: /m, "the script names itself, as its other failures do");
    assert.doesNotMatch(r.stderr, /^\s+at /m, "a raw stack trace is not this script's error convention");
    assert.equal(existsSync(out), false, "nothing is written");
  } finally {
    chmodSync(locked, 0o755);
    rmSync(root, { recursive: true, force: true });
  }
});

// The snapshot on disk is an input to an additive refresh, not just its destination, so a
// malformed one has to be reported the way every other failure here is rather than overwritten —
// silently replacing it would throw away exactly the ids the merge exists to keep.
test("refresh CLI: a malformed existing snapshot reports the script's prefixed error, not a stack trace", () => {
  const root = corpus({ "sess-one": [turn("claude-opus-5")] });
  const out = join(root, "out.json");
  writeFileSync(out, "{ not a json array }");
  const r = spawnSync(process.execPath, [REFRESH, "--dir", root, "--out", out], {
    encoding: "utf8",
    env: { ...process.env, HOME: root },
  });
  try {
    assert.notEqual(r.status, 0, "an unreadable snapshot is an error, not an overwrite");
    assert.match(r.stderr, /^refresh-observed-models: /m, "the script names itself, as its other failures do");
    assert.doesNotMatch(r.stderr, /^\s+at /m, "a raw stack trace is not this script's error convention");
    assert.equal(readFileSync(out, "utf8"), "{ not a json array }", "the malformed snapshot is left alone");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

// atomicWrite writes its temp file beside the target, so an --out under a directory that does not
// exist fails inside the write rather than at flag parsing.
test("refresh CLI: an --out under a missing directory reports the script's prefixed error, not a stack trace", () => {
  const root = corpus({ "sess-one": [turn("claude-opus-5")] });
  const out = join(root, "no-such-dir", "out.json");
  const r = spawnSync(process.execPath, [REFRESH, "--dir", root, "--out", out], {
    encoding: "utf8",
    env: { ...process.env, HOME: root },
  });
  try {
    assert.notEqual(r.status, 0, "an unwritable destination is an error");
    assert.match(r.stderr, /^refresh-observed-models: /m, "the script names itself, as its other failures do");
    assert.doesNotMatch(r.stderr, /^\s+at /m, "a raw stack trace is not this script's error convention");
    assert.equal(existsSync(out), false, "nothing is written");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("PRICING: fable is priced above opus, not below it", () => {
  assert.ok(PRICING.models["claude-fable-5"].in > PRICING.models["claude-opus-5"].in);
  assert.ok(PRICING.models["claude-fable-5"].out > PRICING.models["claude-opus-5"].out);
});

test("PRICING: fable 5.1 is priced above opus, like fable 5", () => {
  assert.ok(PRICING.models["claude-fable-5-1"].in > PRICING.models["claude-opus-5"].in);
  assert.ok(PRICING.models["claude-fable-5-1"].out > PRICING.models["claude-opus-5"].out);
});

test("priceFor: a known id returns its entry", () => {
  assert.deepEqual(priceFor("claude-sonnet-5"), { in: 2, out: 10, window: 1_000_000 });
});

test("priceFor: an unknown id returns null rather than a default", () => {
  assert.equal(priceFor("claude-opus-9"), null);
  assert.equal(priceFor(undefined), null);
  assert.equal(priceFor(""), null);
});

test("PRICING: the table is frozen so no caller can mutate prices at runtime", () => {
  assert.throws(() => {
    PRICING.models["claude-opus-5"] = { in: 0, out: 0, window: 1 };
  }, TypeError);
});
